grails-app/domain/com/damngoodbiscuits/Category.groovy
package com.damngoodbiscuits

class Category {

  String title

    static constraints = {
      blank:false
    }
}

grails-app/controllers/com/damngoodbiscuits/CategoryController.groovy
package com.damngoodbiscuits

import grails.plugin.springsecurity.annotation.Secured

@Secured(['ROLE_ADMIN', 'ROLE_USER'])
class CategoryController {
    static layout = 'admin'
    static scaffold = Category

}

grails-app/views/category/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <g:set var="entityName" value="${message(code: 'category.label', default: 'Category')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <div id="create-category" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message alert-info alert-dismissable" role="status">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                ${flash.message}
            </div>
            </g:if>
            <g:hasErrors bean="${this.category}">
            <div class="alert alert-danger">
                <ul class="errors" role="alert">
                    <g:eachError bean="${this.category}" var="error">
                    <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                    </g:eachError>
                </ul>
            </div>
            </g:hasErrors>
            <g:form action="save" class="form-horizontal">
                <fieldset class="form">
                    <div class="form-group">
                        <label for="title" class="col-sm-1 control-label">Title:
                        </label>
                        <div class="col-sm-10">
                            <g:textField name="title" class="form-control" />                            
                        </div>
                    </div>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save btn btn-primary" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                    <g:link controller="category" onclick="return confirm('Are you sure???')" class="btn btn-default">Cancel</g:link>
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/category/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <g:set var="entityName" value="${message(code: 'category.label', default: 'Category')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <div id="edit-category" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message alert alert-info alert-dismissable" role="status">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                ${flash.message}
            </div>
            </g:if>
            <g:hasErrors bean="${this.category}">
            <div class="alert alert-danger">
                <ul class="errors" role="alert">
                    <g:eachError bean="${this.category}" var="error">
                    <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                    </g:eachError>
                </ul>
            </div>
            </g:hasErrors>
            <g:form resource="${this.category}" method="PUT" class="form-horizontal">
                <g:hiddenField name="version" value="${this.category?.version}" />
                <fieldset class="form">
                    <div class="form-group">
                        <label for="title" class="col-sm-1 control-label">Title:
                        </label>
                        <div class="col-sm-10">
                            <g:textField name="title" class="form-control" value="${this.category.title}" />                            
                        </div>
                    </div>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save btn btn-primary" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                    <g:link controller="category" onclick="return confirm('Are you sure???')" class="btn btn-default">Cancel</g:link>
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/category/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <g:set var="entityName" value="${message(code: 'category.label', default: 'Category')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <div id="list-category" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message alert alert-info alert-dismissable" role="status">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    ${flash.message}
                </div>
            </g:if>
            
            <div class="table-responsive">
            <table class="table table-striped">
                <tr>
                    <th>ID</th>
                    <g:sortableColumn property="title" title="Title" />
                    <th></th>
                </tr>
                <g:each in="${categoryList}" var="catg">
                <tr>
                    <td>${catg.id}</td>
                    <td><g:link action="show" id="${catg.id}">${catg.title}</g:link></td>
                    <td>
                    <g:form resource="${catg}" method="DELETE">
                        <fieldset class="buttons">
                            <g:link class="edit btn btn-primary btn-sm" style="color:white;" action="edit" resource="${catg}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                            <input class="delete btn btn-danger btn-sm" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                        </fieldset>
                    </g:form>
                    </td>
                </tr>
                </g:each>
            </table>
            </div>
            
            <g:link class="btn btn-primary" action="create">Create Category</g:link>

            <div class="pagination">
                <g:paginate total="${categoryCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/category/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <g:set var="entityName" value="${message(code: 'category.label', default: 'Category')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <div id="show-category" class="content scaffold-show" role="main">
            <g:if test="${flash.message}">
                <div class="message alert alert-info alert-dismissable" role="status">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    ${flash.message}
                </div>
            </g:if>
            
            <h1>Category: ${this.category.title}</h1>
            
            <g:form resource="${this.category}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit btn btn-primary" action="edit" resource="${this.category}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete btn btn-danger" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>